package dbms.exececution;

/**
 * This exception is thrown whenever we try to insert in the database a string which is
 * more than 50 characters long.
 *
 */
public class EnormousCharacterException extends Exception
{


	/**
	 * The autogenerated serialVersionUID.
	 */
	
	private static final long serialVersionUID = -7008726936564993487L;


	/**
	 * An empty constructor.
	 */
	
	public EnormousCharacterException()
	{
		super();
	}

	/**
	 * @param message The message of the exception.
	 */
	
	public EnormousCharacterException(String message)
	{
		super(message);
	}

}
